flask-demo/models/blog.py
import time

from . import Model


class Blog(Model):
    def __init__(self, form):
        self.id = None
        self.author = form.get('author', '')
        self.title = form.get('title', '')
        self.content = form.get('content', '')
        self.ct = int(time.time())


class BlogComment(Model):
    def __init__(self, form):
        self.id = None
        self.content = form.get('content', '')
        self.author = form.get('author', '')
        self.blog_id = int(form.get('blog_id', -1))
        self.ct = int(time.time())

flask-demo/models/comment.py
import time

from . import Model


class Comment(Model):
    @classmethod
    def new(cls, form):
        t = cls(form)
        t.save()
        return t

    def __init__(self, form):
        self.id = None
        self.author = form.get('author', '')
        self.content = form.get('content', '')
        self.ct = int(time.time())

flask-demo/routes/blog.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from models.blog import (
    Blog,
    BlogComment,
)
from utils import log

main = Blueprint('blog', __name__)

"""
1. 拆分有哪些页面 一个页面就可以了
    1.1 发博客 link 点进去以后能进入发博客的页面
    1.2 具体的博客，博客的标题，可以被点击
    2.1 博客正文，作者，title，时间，内容
    2.2 发表评论的窗口，发表的评论，都是针对这个博客的
    2.3 显示所有评论的地方，这里面会有评论
    3.1 创建 blog 的页面

2. 组织哪些数据，把数据的操作实现
blog 数据结构
1. id int
2. author string
3. content string
4. time int

blog 数据的方法
1. 新建博客
2. 根据 blog id 拿到一个 blog

blog comment
1. id int
2. author string
3. comment string
4. time int
5. blog_id 也应该被索引

blog comment 操作
1. new
2. blog_id 查询

数据结构 + 数据方法 => 类

3. 逻辑
    3.1 add 的时候创建 blog，然后跳转 /blog/new 这个页面
    3.2 创建完毕，回到 index
    3.3 点击某个 blog，进入 blog 的详细页
    3.4 在详情页，提交一条评论，跳转回来，显示评论

4，开始实现代码，部分对，部分todo
5，剩下的部分一点点补全
6，美化页面
7，交互
"""


@main.route('/')
def index():
    blogs = Blog.all()
    return render_template('blog.html', blogs=blogs)


@main.route('/add', methods=['POST'])
def add():
    form = request.form
    Blog.new(form)
    return redirect(url_for('.index'))


@main.route('/new', methods=['GET'])
def new():
    return render_template('blog_new.html')


@main.route('/<int:blog_id>', methods=['GET'])
def view(blog_id):
    comments = BlogComment.find_all(blog_id=blog_id)
    blog = Blog.find(blog_id)
    return render_template('blog_view.html', blog=blog, comments=comments)


@main.route('/comment/new', methods=['POST'])
def comment():
    form = request.form
    BlogComment.new(form)
    blog_id = form.get('blog_id', -1)
    return redirect(url_for('.view', blog_id=blog_id))

flask-demo/routes/comment.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)


from models.comment import Comment
from utils import log

# 创建一个 蓝图对象 并且路由定义在蓝图对象中
# 然后在 flask 主代码中「注册蓝图」来使用
# 第一个参数是蓝图的名字, 以后会有用(add函数里面就用到了)
# 第二个参数是套路
main = Blueprint('comment', __name__)


"""
1. 拆分有哪些页面 一个页面就可以了
--- author --- content --- button ---

--- comment ---
--- comment ---
.....

2. 组织哪些数据，把数据的操作实现
comment 数据结构
1. id
2. author string
3. content string
4. time int

comment 数据的方法
1. 新建评论
2. 所有的评论

数据结构 + 数据方法 => 类

3. 逻辑
    3.1 add 的时候增加一个评论，然后跳转回到主页，在主页显示所有评论
    
4，开始实现代码，部分对，部分todo
5，剩下的部分一点点补全
6，美化页面
7，交互
"""


@main.route('/')
def index():
    comments = Comment.all()
    return render_template('comment.html', comments=comments)


@main.route('/add', methods=['POST'])
def add():
    t = Comment.new(request.form)
    return redirect(url_for('.index'))

flask-demo/routes/todo.py
from flask import (
    render_template,
    request,
    flash,
    redirect,
    url_for,
    Blueprint,
)

from models.todo import Todo


# 创建一个 蓝图对象 并且路由定义在蓝图对象中
# 然后在 flask 主代码中「注册蓝图」来使用
# 第一个参数是蓝图的名字, 以后会有用(add函数里面就用到了)
# 第二个参数是套路
main = Blueprint('todo', __name__)


@main.route('/')
def index():
    # 查找所有的 routes 并返回
    todo_list = Todo.all()
    # flask 已经配置好了 jinjia2 模板引擎
    # 并且可以直接使用 render_template 来生成相应数据（http_response）
    return render_template('todo_index.html', todos=todo_list)


@main.route('/add', methods=['POST'])
def add():
    form = request.form
    t = Todo.new(form)
    # 蓝图中的 url_for 需要加上蓝图的名字，这里是 routes
    return redirect(url_for('todo.index'))


@main.route('/delete/<int:todo_id>/')
def delete(todo_id):
    """
    <int:todo_id> 的方式可以匹配一个 int 类型
    int 指定了它的类型，省略的话参数中的 todo_id 就是 str 类型

    这个概念叫做 动态路由
    意思是这个路由函数可以匹配一系列不同的路由

    动态路由是现在流行的路由设计方案
    """
    # 通过 id 删除 routes
    t = Todo.delete(todo_id)
    # 引用蓝图内部的路由函数的时候，可以省略名字只用 .
    # 因为我们就在 routes 这个蓝图里面, 所以可以省略 routes
    # return redirect(url_for('todo.index'))
    return redirect(url_for('.index'))

flask-demo/templates/blog.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>博客主页</title>
</head>
<body>
<a href={{ url_for(".new") }}>新建博客</a>
<div>
    {% for b in blogs %}
        <div>
        <a href= {{ url_for(".view", blog_id=b.id) }}>
        {{ b.title }} @ {{ b.time() }} by {{ b.author }}
        </a>
        </div>
    {% endfor %}
</div>

</body>
</html>

flask-demo/templates/blog_new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>发表新博文</title>
</head>
<body>
<form method="POST" action={{ url_for('.add') }}>
    <input type="text" name="author" placeholder="author">
    <input type="text" name="title" placeholder="title">
    <br>
    <textarea name="content" placeholder="content">
    </textarea>
    <br>
    <button type="submit">发布</button>
</form>

</body>
</html>

flask-demo/templates/blog_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ blog.title }}</title>
</head>
<h1>{{ blog.title }}</h1>
<h3>{{ blog.author }}</h3>
<p>{{ blog.content }}</p>

<form method="post" action="comment/new">
    <input type="text" name="author" placeholder="author">
    <input type="text" name="content" placeholder="content">
    <input type="hidden" name="blog_id" value={{ blog.id }}>
    <button type="submit">提交评论</button>
</form>

<div>
    {% for c in comments %}
        <div>{{ c.content }} @ {{ c.author }}</div>
    {% endfor %}
</div>
<body>

</body>
</html>

flask-demo/templates/comment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>留言板</title>
</head>
<body>
    <form method="POST" action={{ url_for('.add') }}>
        <input type="text" name="author" placeholder="author">
        <input type="text" name="content" placeholder="content">
        <button type="submit">提交</button>
    </form>
    <div>
        {% for c in comments %}
            <div>{{ c.content }} from {{ c.author }} @ {{ c.time() }}</div>
        {% endfor %}
    </div>
</body>
</html>

flask-demo/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>主页</title>
</head>
<body>
    <h1>{{ user }}</h1>
    <h2>
        <a href="{{ url_for('.profile') }}">个人资料页面</a>
    </h2>
    <form method="post" action="{{ url_for('.register') }}">
        <input name="username">
        <br>
        <input name="password">
        <br>
        <button type="submit">注册</button>
    </form>
    <form method="post" action="{{ url_for('.login') }}">
        <input name="username">
        <br>
        <input name="password">
        <br>
        <button type="submit">登录</button>
    </form>
</body>
</html>

flask-demo/templates/jinja_demo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>jinja demo</title>
</head>
<body>
    <!-- 变量替换 -->
    <h1>{{ name }}</h1>

    <!-- 循环 -->
    {% for n in numbers %}
        <span class="number">{{ n }}</span>
    {% endfor %}

    <!-- 循环加对象/字典访问 -->
    <div class="user-container">
    {% for u in users %}
        <div class="user-cell">
            <span>{{ u.name }}</span>
            <span>{{ u.id }}</span>
        </div>
    {% endfor %}
    </div>

    <!-- TODO: 更多语法 -->
</body>
</html>

flask-demo/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="POST" action={{ url_for(".login") }}>
    <input type="text" name="username" placeholder="username">
    <button type="submit">提交</button>
</form>
</body>
</html>

flask-demo/templates/message_index.html
<!DOCTYPE html>
<html>
<head>
    <!-- 指明字符编码为 utf-8 否则中文会乱码 -->
    <meta charset="utf-8">
    <title>留言板</title>
</head>
<body>
    <h1>留言板</h1>
    <form action="/message" method="GET">
        这是一个发送 GET 请求的表单
        <br>
        <textarea name="msg"></textarea>
        <br>
        <button type="submit">用 GET 提交表单</button>
    </form>

    <form action="/message/add" method="POST">
        这是一个发送 POST 请求的表单
        <br>
        <textarea name="msg_post"></textarea>
        <br>
        <button type="submit">用 POST 提交表单</button>
    </form>
    <!-- 下面是使用模板的办法 -->
    {# 这是 Jinja2 模板的注释语法，这样的注释并不会在生成的 HTML 代码中出现 #}
    {# {% %} 里面的是语句 #}
    {# {{ }} 里面的是引用变量 #}
    <!-- 注意 m 本身是一个字典，但是你可以用 . 的语法来引用 -->
    <!-- 这是 Jinja2 模板的功能 -->
    {% for m in messages %}
        <div>{{ m.content }}</div>
    {% endfor %}
</body>
</html>

flask-demo/templates/session_index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p> hello {{ username }}!</p>
<form method="get" action={{ url_for(".logout") }}>
    <button type="submit">退出登录</button>
</form>
</body>
</html>

flask-demo/templates/todo_index.html
<html>
<head>
    <title>Todo</title>
    <!-- 静态文件放在 /static 文件夹中 -->
    <!-- 引用路径是 /static/... -->
    <link rel="stylesheet" href="/static/css/pure-min.css">
    <style type="text/css">
    .todo-table {
        margin: 0 auto;
    }
    .center {
        text-align: center;
    }
    </style>
</head>

<body>
    <div class="center">
        <h1>Todo</h1>
        <!-- 注意这里 的 url_for 也是需要加上蓝图名字前缀的 -->
        <form action={{ url_for("todo.add") }} method="post">
            <input type="text" placeholder="Add Todo" name="title">
            <input class="pure-button pure-button-primary" type="submit" value="Add">
        </form>
    </div>

    <table class="todo-table pure-table pure-table-horizontal pure-table-striped">
        <thead>
            <tr>
                <th>#</th>
                <th>Title</th>
                <th>Time</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
        {% for t in todos %}
            <tr>
                <td>{{ t.id }}</td>
                <td>{{ t.title }}</td>
                <td>{{ t.time() }}</td>
                <!-- url_for 可以传递参数，先匹配动态路由，如果动态路由匹配失败则变成 query 参数 -->
                <td><a href={{ url_for('todo.delete', todo_id=t.id) }}>delete</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</body>
</html>